// <auto-generated />
using EducaFlow.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EducaFlow.Migrations.Serie
{
    [DbContext(typeof(SerieContext))]
    partial class SerieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EducaFlow.Models.Curso", b =>
                {
                    b.Property<int>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCurso"));

                    b.Property<int>("CodCurso")
                        .HasColumnType("int");

                    b.Property<int>("NiveisEnsino")
                        .HasColumnType("int");

                    b.Property<string>("NomeCurso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QtdEtapas")
                        .HasColumnType("int");

                    b.Property<string>("SiglaCurso")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCurso");

                    b.ToTable("Curso");
                });

            modelBuilder.Entity("EducaFlow.Models.Serie", b =>
                {
                    b.Property<int>("IdSerie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSerie"));

                    b.Property<float>("CargaHoraria")
                        .HasColumnType("real");

                    b.Property<int>("CodSerie")
                        .HasColumnType("int");

                    b.Property<bool>("Concluinte")
                        .HasColumnType("bit");

                    b.Property<int>("CursoIdCurso")
                        .HasColumnType("int");

                    b.Property<int>("DiasLetivos")
                        .HasColumnType("int");

                    b.Property<int>("EtapaCurso")
                        .HasColumnType("int");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.Property<string>("NomeSerie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegraAvaliacao")
                        .HasColumnType("int");

                    b.HasKey("IdSerie");

                    b.HasIndex("CursoIdCurso");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("EducaFlow.Models.Serie", b =>
                {
                    b.HasOne("EducaFlow.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoIdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });
#pragma warning restore 612, 618
        }
    }
}
